name: YouTube Auto Bot

concurrency:
  group: youtube-bot
  cancel-in-progress: true

on:
  workflow_dispatch:

    # test 

  schedule:
    - cron:  '*/10 * * * *'
  
    # 7:00 AM Myanmar
    - cron: '30 0 * * *'

    # 12:00 PM Myanmar
    - cron: '30 5 * * *'

    # 7:00 PM Myanmar
    - cron: '30 12 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install FFmpeg + Python
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3 python3-pip

      - name: Install edge-tts
        run: pip3 install edge-tts

      - name: Install Node Packages
        run: npm install

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: node index.js