name: Telegram Cloud Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install FFmpeg + Python
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3 python3-pip

      - name: Install Python Packages
        run: |
          pip3 install -r requirements.txt

      - name: Install Node Packages
        run: |
          npm install

      - name: Start Next Loop Trigger In Background
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          nohup bash -c '
            sleep 20400
            curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token '$GH_PAT'" \
            https://api.github.com/repos/phoethae2347-dotcom/yt-auto-bot1/actions/workflows/bot.yml/dispatches \
            -d "{\"ref\":\"main\"}"
          ' >/dev/null 2>&1 &

      - name: Run Telegram AI Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
        run: |
          node index.js